// Wavelength prompts.
//
// Schema: { left, right, difficulty, category }
//   left/right  – the two endpoints of the spectrum
//   difficulty  – "easy"  consensus extremes (food, smells, weather, basic objects)
//                 "hard"  subjective, niche, abstract, or taste-driven
//   category    – one of the keys in CATEGORIES below
//
// The game picks randomly and never repeats within a single session.
// Players can disable individual prompts via the "View Prompt Cards" screen;
// disabled prompts are excluded from future games.
// Add, remove, or edit freely – just keep the shape consistent.

export const CATEGORIES = {
  food:          { label: "Food & Drink",                hue: 18  },
  animals:       { label: "Animals",                     hue: 130 },
  entertainment: { label: "Entertainment",               hue: 280 },
  tech:          { label: "Tech & Internet",             hue: 200 },
  home:          { label: "Home, Objects & Style",       hue: 35  },
  travel:        { label: "Travel & Places",             hue: 170 },
  people:        { label: "People & Relationships",      hue: 340 },
  work:          { label: "Work, School & Money",        hue: 50  },
  activities:    { label: "Activities, Sports & Hobbies", hue: 100 },
  events:        { label: "Holidays & Events",           hue: 0   },
  body:          { label: "Body, Health & Senses",       hue: 320 },
  imagination:   { label: "Imagination & Abstract",      hue: 250 },
};

// Stable content-based key. Used for persisting user toggle state without
// being broken by prompt reordering.
export const promptKey = (p) => `${p.left}‖${p.right}`;

export const PROMPTS = [
  // ─── Originals (re-bucketed thematically) ─────────────────────────────
  { left: "Terrible superpower", right: "Amazing superpower", difficulty: "easy", category: "imagination" },
  { left: "Worst way to die", right: "Best way to die", difficulty: "hard", category: "imagination" },
  { left: "Bad pizza topping", right: "Great pizza topping", difficulty: "easy", category: "food" },
  { left: "Forgettable movie", right: "Unforgettable movie", difficulty: "hard", category: "entertainment" },
  { left: "Boring hobby", right: "Fascinating hobby", difficulty: "hard", category: "activities" },
  { left: "Useless invention", right: "World-changing invention", difficulty: "hard", category: "tech" },
  { left: "Awful first date", right: "Perfect first date", difficulty: "easy", category: "people" },
  { left: "Terrible pet", right: "Perfect pet", difficulty: "easy", category: "animals" },
  { left: "Bad thing to say at a wedding", right: "Great thing to say at a wedding", difficulty: "easy", category: "events" },
  { left: "Overrated", right: "Underrated", difficulty: "hard", category: "imagination" },
  { left: "Worst smell", right: "Best smell", difficulty: "easy", category: "body" },
  { left: "Bad Halloween costume", right: "Iconic Halloween costume", difficulty: "easy", category: "events" },
  { left: "Nobody wants this skill", right: "Everyone wants this skill", difficulty: "hard", category: "work" },
  { left: "Terrible band name", right: "Incredible band name", difficulty: "hard", category: "entertainment" },
  { left: "Worst celebrity to be stuck in an elevator with", right: "Best celebrity to be stuck in an elevator with", difficulty: "hard", category: "entertainment" },
  { left: "Bad life advice", right: "Great life advice", difficulty: "easy", category: "imagination" },
  { left: "Least cool animal", right: "Coolest animal", difficulty: "easy", category: "animals" },
  { left: "Worst thing to find in your pocket", right: "Best thing to find in your pocket", difficulty: "easy", category: "home" },
  { left: "Terrible restaurant theme", right: "Amazing restaurant theme", difficulty: "hard", category: "food" },
  { left: "Not impressive at all", right: "Extremely impressive", difficulty: "hard", category: "imagination" },
  { left: "Worst thing to be famous for", right: "Best thing to be famous for", difficulty: "hard", category: "entertainment" },
  { left: "Bad vacation destination", right: "Dream vacation destination", difficulty: "easy", category: "travel" },
  { left: "Least satisfying sound", right: "Most satisfying sound", difficulty: "easy", category: "body" },
  { left: "Terrible middle name", right: "Awesome middle name", difficulty: "hard", category: "people" },
  { left: "Worst age to be", right: "Best age to be", difficulty: "hard", category: "people" },
  { left: "Bad thing to automate", right: "Great thing to automate", difficulty: "hard", category: "tech" },
  { left: "Least romantic gesture", right: "Most romantic gesture", difficulty: "easy", category: "people" },
  { left: "Worst food to eat on a first date", right: "Best food to eat on a first date", difficulty: "easy", category: "food" },
  { left: "Useless in a zombie apocalypse", right: "Essential in a zombie apocalypse", difficulty: "easy", category: "imagination" },
  { left: "Bad tattoo idea", right: "Great tattoo idea", difficulty: "hard", category: "home" },
  { left: "Worst Olympic sport to add", right: "Best Olympic sport to add", difficulty: "hard", category: "activities" },
  { left: "Least intimidating", right: "Most intimidating", difficulty: "easy", category: "imagination" },
  { left: "Terrible thing to whisper to a stranger", right: "OK thing to whisper to a stranger", difficulty: "easy", category: "people" },
  { left: "Worst historical era to live in", right: "Best historical era to live in", difficulty: "easy", category: "imagination" },
  { left: "Least fun game", right: "Most fun game", difficulty: "hard", category: "activities" },
  { left: "Bad reason to call 911", right: "Good reason to call 911", difficulty: "easy", category: "imagination" },
  { left: "Worst thing to step on barefoot", right: "Best thing to step on barefoot", difficulty: "easy", category: "home" },
  { left: "Least useful school subject", right: "Most useful school subject", difficulty: "hard", category: "work" },
  { left: "Worst thing to forget", right: "Best thing to forget", difficulty: "hard", category: "imagination" },
  { left: "Terrible Wi-Fi password", right: "Clever Wi-Fi password", difficulty: "hard", category: "tech" },
  { left: "Worst way to start a speech", right: "Best way to start a speech", difficulty: "easy", category: "people" },
  { left: "Least relaxing", right: "Most relaxing", difficulty: "easy", category: "body" },
  { left: "Bad thing to collect", right: "Cool thing to collect", difficulty: "hard", category: "home" },
  { left: "Worst song to wake up to", right: "Best song to wake up to", difficulty: "hard", category: "entertainment" },
  { left: "Terrible party theme", right: "Amazing party theme", difficulty: "hard", category: "events" },
  { left: "Least trustworthy profession", right: "Most trustworthy profession", difficulty: "hard", category: "work" },
  { left: "Worst thing to drop from a building", right: "Funniest thing to drop from a building", difficulty: "easy", category: "imagination" },
  { left: "Bad name for a boat", right: "Perfect name for a boat", difficulty: "hard", category: "travel" },
  { left: "Least photogenic", right: "Most photogenic", difficulty: "hard", category: "people" },
  { left: "Worst excuse for being late", right: "Most creative excuse for being late", difficulty: "hard", category: "work" },
  { left: "Terrible ice cream flavor", right: "Best ice cream flavor", difficulty: "easy", category: "food" },
  { left: "Least rewatchable movie", right: "Most rewatchable movie", difficulty: "hard", category: "entertainment" },
  { left: "Bad last words", right: "Legendary last words", difficulty: "hard", category: "imagination" },
  { left: "Worst way to propose", right: "Best way to propose", difficulty: "hard", category: "people" },
  { left: "Least comforting", right: "Most comforting", difficulty: "easy", category: "imagination" },
  { left: "Terrible thing to put on a resume", right: "Impressive thing to put on a resume", difficulty: "hard", category: "work" },
  { left: "Worst thing to say to your boss", right: "Best thing to say to your boss", difficulty: "easy", category: "work" },
  { left: "Least cool way to arrive", right: "Coolest way to arrive", difficulty: "hard", category: "people" },
  { left: "Bad thing to yell in a library", right: "OK thing to yell in a library", difficulty: "hard", category: "people" },
  { left: "Worst childhood memory", right: "Best childhood memory", difficulty: "easy", category: "people" },
  { left: "Least appetizing food color", right: "Most appetizing food color", difficulty: "easy", category: "food" },
  { left: "Terrible password", right: "Uncrackable password", difficulty: "easy", category: "tech" },
  { left: "Worst ride at a theme park", right: "Best ride at a theme park", difficulty: "hard", category: "travel" },
  { left: "Least charismatic", right: "Most charismatic", difficulty: "hard", category: "people" },
  { left: "Bad thing to name your child", right: "Great thing to name your child", difficulty: "hard", category: "people" },
  { left: "Worst item to have only one of", right: "Best item to have only one of", difficulty: "hard", category: "home" },
  { left: "Least useful kitchen gadget", right: "Most useful kitchen gadget", difficulty: "easy", category: "home" },
  { left: "Terrible thing to say in a job interview", right: "Perfect thing to say in a job interview", difficulty: "easy", category: "work" },
  { left: "Worst breakfast food", right: "Best breakfast food", difficulty: "easy", category: "food" },
  { left: "Least scary monster", right: "Most terrifying monster", difficulty: "easy", category: "imagination" },
  { left: "Bad road trip car", right: "Perfect road trip car", difficulty: "easy", category: "travel" },
  { left: "Worst compliment", right: "Best compliment", difficulty: "easy", category: "people" },
  { left: "Least useful app", right: "Most useful app", difficulty: "hard", category: "tech" },
  { left: "Terrible alarm sound", right: "Perfect alarm sound", difficulty: "easy", category: "body" },
  { left: "Worst thing to sit next to on a plane", right: "Best thing to sit next to on a plane", difficulty: "easy", category: "travel" },
  { left: "Least fun chore", right: "Most satisfying chore", difficulty: "easy", category: "home" },
  { left: "Bad thing to be allergic to", right: "Good thing to be allergic to", difficulty: "easy", category: "body" },
  { left: "Worst conspiracy theory", right: "Most believable conspiracy theory", difficulty: "hard", category: "imagination" },
  { left: "Least festive", right: "Most festive", difficulty: "easy", category: "events" },
  { left: "Terrible thing to automate with AI", right: "Perfect thing to automate with AI", difficulty: "hard", category: "tech" },
  { left: "Worst sandwich filling", right: "Best sandwich filling", difficulty: "easy", category: "food" },
  { left: "Least athletic activity", right: "Most athletic activity", difficulty: "easy", category: "activities" },
  { left: "Bad theme for a wedding", right: "Amazing theme for a wedding", difficulty: "hard", category: "events" },
  { left: "Worst thing to lose", right: "Best thing to lose", difficulty: "easy", category: "imagination" },
  { left: "Least funny joke topic", right: "Funniest joke topic", difficulty: "hard", category: "entertainment" },
  { left: "Terrible thing to 3D print", right: "Coolest thing to 3D print", difficulty: "hard", category: "tech" },
  { left: "Worst museum exhibit", right: "Best museum exhibit", difficulty: "hard", category: "travel" },
  { left: "Least portable", right: "Most portable", difficulty: "easy", category: "home" },
  { left: "Bad thing to bring camping", right: "Essential thing to bring camping", difficulty: "easy", category: "activities" },
  { left: "Worst text to send to the wrong person", right: "Harmless text to send to the wrong person", difficulty: "easy", category: "tech" },
  { left: "Least dramatic", right: "Most dramatic", difficulty: "easy", category: "entertainment" },
  { left: "Terrible trivia category", right: "Best trivia category", difficulty: "hard", category: "activities" },
  { left: "Worst way to spend a million dollars", right: "Best way to spend a million dollars", difficulty: "hard", category: "work" },
  { left: "Least nostalgic", right: "Most nostalgic", difficulty: "hard", category: "imagination" },
  { left: "Bad thing to do in zero gravity", right: "Awesome thing to do in zero gravity", difficulty: "easy", category: "imagination" },
  { left: "Worst thing to run out of", right: "Best thing to run out of", difficulty: "easy", category: "home" },
  { left: "Least iconic", right: "Most iconic", difficulty: "hard", category: "imagination" },
  { left: "Terrible voicemail greeting", right: "Best voicemail greeting", difficulty: "hard", category: "tech" },
  { left: "Worst thing to discover about your neighbor", right: "Best thing to discover about your neighbor", difficulty: "easy", category: "people" },
  { left: "Least futuristic", right: "Most futuristic", difficulty: "easy", category: "imagination" },

  // ─── Food & Drink ─────────────────────────────────────────────────────
  { left: "Worst hot dog topping", right: "Best hot dog topping", difficulty: "easy", category: "food" },
  { left: "Sketchy coffee order", right: "Impressive coffee order", difficulty: "hard", category: "food" },
  { left: "Worst sandwich bread", right: "Best sandwich bread", difficulty: "easy", category: "food" },
  { left: "Suspicious food color", right: "Trustworthy food color", difficulty: "easy", category: "food" },
  { left: "Worst birthday cake flavor", right: "Best birthday cake flavor", difficulty: "easy", category: "food" },
  { left: "Bad food to eat in bed", right: "Acceptable food to eat in bed", difficulty: "easy", category: "food" },
  { left: "Least snackable", right: "Most snackable", difficulty: "hard", category: "food" },
  { left: "Worst thing to put on toast", right: "Best thing to put on toast", difficulty: "easy", category: "food" },
  { left: "Disappointing leftovers", right: "Exciting leftovers", difficulty: "easy", category: "food" },
  { left: "Worst airport food", right: "Surprisingly good airport food", difficulty: "hard", category: "food" },
  { left: "Bad excuse to order takeout", right: "Great excuse to order takeout", difficulty: "hard", category: "food" },
  { left: "Worst pasta shape", right: "Best pasta shape", difficulty: "hard", category: "food" },
  { left: "Worst gas station snack", right: "Best gas station snack", difficulty: "easy", category: "food" },
  { left: "Saddest meal", right: "Most comforting meal", difficulty: "easy", category: "food" },
  { left: "Least hydrating drink", right: "Most hydrating drink", difficulty: "easy", category: "food" },
  { left: "Worst pizza shape", right: "Best pizza shape", difficulty: "hard", category: "food" },
  { left: "Bad cheese on a burger", right: "Great cheese on a burger", difficulty: "easy", category: "food" },
  { left: "Worst dessert", right: "Best dessert", difficulty: "hard", category: "food" },
  { left: "Bad cooking smell", right: "Amazing cooking smell", difficulty: "easy", category: "food" },
  { left: "Worst restaurant background noise", right: "Best restaurant background noise", difficulty: "easy", category: "food" },
  { left: "Bad food to eat with chopsticks", right: "Easy food to eat with chopsticks", difficulty: "easy", category: "food" },
  { left: "Worst breakfast cereal", right: "Best breakfast cereal", difficulty: "easy", category: "food" },
  { left: "Saddest sandwich", right: "Triumphant sandwich", difficulty: "hard", category: "food" },
  { left: "Worst soup to spill on yourself", right: "Least bad soup to spill on yourself", difficulty: "easy", category: "food" },
  { left: "Bad way to drink water", right: "Refreshing way to drink water", difficulty: "hard", category: "food" },

  // ─── Animals ──────────────────────────────────────────────────────────
  { left: "Worst pet for a small apartment", right: "Best pet for a small apartment", difficulty: "easy", category: "animals" },
  { left: "Least huggable animal", right: "Most huggable animal", difficulty: "easy", category: "animals" },
  { left: "Worst zoo exhibit", right: "Best zoo exhibit", difficulty: "hard", category: "animals" },
  { left: "Bad name for a dog", right: "Perfect name for a dog", difficulty: "hard", category: "animals" },
  { left: "Bad name for a goldfish", right: "Perfect name for a goldfish", difficulty: "hard", category: "animals" },
  { left: "Least majestic animal", right: "Most majestic animal", difficulty: "easy", category: "animals" },
  { left: "Worst animal to ride", right: "Best animal to ride", difficulty: "easy", category: "animals" },
  { left: "Least graceful animal", right: "Most graceful animal", difficulty: "easy", category: "animals" },
  { left: "Worst pet to walk", right: "Best pet to walk", difficulty: "easy", category: "animals" },
  { left: "Bad farm animal", right: "Great farm animal", difficulty: "hard", category: "animals" },
  { left: "Least photogenic dog breed", right: "Most photogenic dog breed", difficulty: "hard", category: "animals" },
  { left: "Worst sound an animal makes", right: "Cutest sound an animal makes", difficulty: "easy", category: "animals" },
  { left: "Saddest extinct animal", right: "Coolest extinct animal", difficulty: "hard", category: "animals" },
  { left: "Worst bug to find indoors", right: "Least bad bug to find indoors", difficulty: "easy", category: "animals" },
  { left: "Worst zoo escape", right: "Funniest zoo escape", difficulty: "hard", category: "animals" },

  // ─── Entertainment (movies, TV, books, music) ─────────────────────────
  { left: "Worst movie to watch with parents", right: "OK movie to watch with parents", difficulty: "easy", category: "entertainment" },
  { left: "Least binge-able show", right: "Most binge-able show", difficulty: "hard", category: "entertainment" },
  { left: "Worst plot twist", right: "Best plot twist", difficulty: "hard", category: "entertainment" },
  { left: "Bad movie to watch on a plane", right: "Perfect movie to watch on a plane", difficulty: "easy", category: "entertainment" },
  { left: "Worst sequel idea", right: "Brilliant sequel idea", difficulty: "hard", category: "entertainment" },
  { left: "Least scary horror movie", right: "Most terrifying horror movie", difficulty: "hard", category: "entertainment" },
  { left: "Worst character to root for", right: "Best character to root for", difficulty: "hard", category: "entertainment" },
  { left: "Bad book title", right: "Bestseller book title", difficulty: "hard", category: "entertainment" },
  { left: "Worst movie ending", right: "Most satisfying movie ending", difficulty: "hard", category: "entertainment" },
  { left: "Least quotable line", right: "Most quotable line", difficulty: "hard", category: "entertainment" },
  { left: "Worst show theme song", right: "Best show theme song", difficulty: "hard", category: "entertainment" },
  { left: "Bad movie villain", right: "Iconic movie villain", difficulty: "easy", category: "entertainment" },
  { left: "Worst documentary topic", right: "Most fascinating documentary topic", difficulty: "hard", category: "entertainment" },
  { left: "Bad rom-com setup", right: "Great rom-com setup", difficulty: "hard", category: "entertainment" },
  { left: "Worst Netflix recommendation", right: "Best Netflix recommendation", difficulty: "hard", category: "entertainment" },
  { left: "Worst karaoke song", right: "Best karaoke song", difficulty: "easy", category: "entertainment" },
  { left: "Bad song for a wedding", right: "Perfect song for a wedding", difficulty: "easy", category: "entertainment" },
  { left: "Least danceable song", right: "Most danceable song", difficulty: "easy", category: "entertainment" },
  { left: "Worst shower song", right: "Best shower song", difficulty: "easy", category: "entertainment" },
  { left: "Bad song at a funeral", right: "Acceptable song at a funeral", difficulty: "easy", category: "entertainment" },
  { left: "Worst instrument to start as an adult", right: "Best instrument to start as an adult", difficulty: "hard", category: "entertainment" },
  { left: "Bad band reunion", right: "Dream band reunion", difficulty: "hard", category: "entertainment" },
  { left: "Least timeless song", right: "Most timeless song", difficulty: "hard", category: "entertainment" },
  { left: "Worst gym song", right: "Best gym song", difficulty: "easy", category: "entertainment" },
  { left: "Bad cover song idea", right: "Inspired cover song idea", difficulty: "hard", category: "entertainment" },

  // ─── Tech & Internet ──────────────────────────────────────────────────
  { left: "Worst smart home device", right: "Best smart home device", difficulty: "easy", category: "tech" },
  { left: "Least useful AI feature", right: "Most useful AI feature", difficulty: "hard", category: "tech" },
  { left: "Bad app icon", right: "Beautiful app icon", difficulty: "hard", category: "tech" },
  { left: "Worst notification sound", right: "Best notification sound", difficulty: "easy", category: "tech" },
  { left: "Bad website name", right: "Memorable website name", difficulty: "hard", category: "tech" },
  { left: "Least practical gadget", right: "Most practical gadget", difficulty: "easy", category: "tech" },
  { left: "Worst keyboard layout", right: "Best keyboard layout", difficulty: "hard", category: "tech" },
  { left: "Bad email signature", right: "Great email signature", difficulty: "hard", category: "tech" },
  { left: "Worst startup name", right: "Best startup name", difficulty: "hard", category: "tech" },
  { left: "Least intuitive UI", right: "Most intuitive UI", difficulty: "hard", category: "tech" },
  { left: "Bad robot name", right: "Perfect robot name", difficulty: "hard", category: "tech" },
  { left: "Worst feature in a phone", right: "Best feature in a phone", difficulty: "easy", category: "tech" },
  { left: "Worst Chrome extension", right: "Best Chrome extension", difficulty: "hard", category: "tech" },
  { left: "Bad video game ending", right: "Best video game ending", difficulty: "hard", category: "tech" },
  { left: "Worst social media platform", right: "Best social media platform", difficulty: "hard", category: "tech" },

  // ─── Home, Objects & Style ────────────────────────────────────────────
  { left: "Worst thing to keep on your nightstand", right: "Best thing to keep on your nightstand", difficulty: "easy", category: "home" },
  { left: "Bad mug design", right: "Great mug design", difficulty: "hard", category: "home" },
  { left: "Least useful office supply", right: "Most useful office supply", difficulty: "easy", category: "home" },
  { left: "Worst keychain", right: "Coolest keychain", difficulty: "hard", category: "home" },
  { left: "Bad house number", right: "Lucky house number", difficulty: "hard", category: "home" },
  { left: "Worst bedsheet pattern", right: "Best bedsheet pattern", difficulty: "hard", category: "home" },
  { left: "Bad gift for a coworker", right: "Great gift for a coworker", difficulty: "easy", category: "home" },
  { left: "Worst fridge magnet", right: "Best fridge magnet", difficulty: "hard", category: "home" },
  { left: "Least comfortable chair", right: "Most comfortable chair", difficulty: "easy", category: "home" },
  { left: "Bad shower curtain", right: "Great shower curtain", difficulty: "hard", category: "home" },
  { left: "Worst houseplant", right: "Best houseplant", difficulty: "easy", category: "home" },
  { left: "Bad place for a plant", right: "Perfect place for a plant", difficulty: "easy", category: "home" },
  { left: "Worst doormat saying", right: "Best doormat saying", difficulty: "hard", category: "home" },
  { left: "Least useful junk drawer item", right: "Most useful junk drawer item", difficulty: "hard", category: "home" },
  { left: "Bad clock design", right: "Great clock design", difficulty: "hard", category: "home" },
  { left: "Worst color combination", right: "Best color combination", difficulty: "easy", category: "home" },
  { left: "Bad font choice", right: "Great font choice", difficulty: "hard", category: "home" },
  { left: "Least Instagrammable", right: "Most Instagrammable", difficulty: "hard", category: "home" },
  { left: "Worst home decor trend", right: "Best home decor trend", difficulty: "hard", category: "home" },
  { left: "Bad logo", right: "Iconic logo", difficulty: "hard", category: "home" },
  { left: "Worst haircut", right: "Best haircut", difficulty: "hard", category: "home" },
  { left: "Bad outfit for a job interview", right: "Great outfit for a job interview", difficulty: "easy", category: "home" },
  { left: "Worst hat", right: "Best hat", difficulty: "hard", category: "home" },
  { left: "Least stylish footwear", right: "Most stylish footwear", difficulty: "hard", category: "home" },
  { left: "Bad bedroom paint color", right: "Great bedroom paint color", difficulty: "hard", category: "home" },

  // ─── Travel & Places ──────────────────────────────────────────────────
  { left: "Worst airline", right: "Best airline", difficulty: "easy", category: "travel" },
  { left: "Bad road trip snack", right: "Perfect road trip snack", difficulty: "easy", category: "travel" },
  { left: "Worst hotel amenity", right: "Best hotel amenity", difficulty: "easy", category: "travel" },
  { left: "Worst seat on a plane", right: "Best seat on a plane", difficulty: "easy", category: "travel" },
  { left: "Bad reason to visit a country", right: "Great reason to visit a country", difficulty: "hard", category: "travel" },
  { left: "Least scenic route", right: "Most scenic route", difficulty: "easy", category: "travel" },
  { left: "Worst suitcase color", right: "Best suitcase color", difficulty: "hard", category: "travel" },
  { left: "Bad airport for a layover", right: "Best airport for a layover", difficulty: "hard", category: "travel" },
  { left: "Worst souvenir", right: "Best souvenir", difficulty: "easy", category: "travel" },
  { left: "Least walkable city", right: "Most walkable city", difficulty: "easy", category: "travel" },

  // ─── People & Relationships ───────────────────────────────────────────
  { left: "Worst icebreaker", right: "Best icebreaker", difficulty: "easy", category: "people" },
  { left: "Bad nickname", right: "Cool nickname", difficulty: "hard", category: "people" },
  { left: "Least flattering photo angle", right: "Most flattering photo angle", difficulty: "hard", category: "people" },
  { left: "Worst thing to say at a funeral", right: "Best thing to say at a funeral", difficulty: "easy", category: "people" },
  { left: "Bad first impression", right: "Great first impression", difficulty: "easy", category: "people" },
  { left: "Worst gift to give an ex", right: "Best gift to give an ex", difficulty: "easy", category: "people" },
  { left: "Least romantic place", right: "Most romantic place", difficulty: "easy", category: "people" },
  { left: "Worst person to share a road trip with", right: "Best person to share a road trip with", difficulty: "easy", category: "people" },
  { left: "Bad question on a first date", right: "Great question on a first date", difficulty: "easy", category: "people" },
  { left: "Worst thing to argue about", right: "Worth arguing about", difficulty: "hard", category: "people" },
  { left: "Least fun cousin", right: "Most fun cousin", difficulty: "hard", category: "people" },
  { left: "Bad emotional support animal", right: "Perfect emotional support animal", difficulty: "easy", category: "people" },
  { left: "Worst toast at a wedding", right: "Best toast at a wedding", difficulty: "hard", category: "people" },
  { left: "Bad apology", right: "Sincere apology", difficulty: "easy", category: "people" },
  { left: "Worst small talk topic", right: "Best small talk topic", difficulty: "hard", category: "people" },

  // ─── Work, School & Money ─────────────────────────────────────────────
  { left: "Worst job to do in winter", right: "Best job to do in winter", difficulty: "easy", category: "work" },
  { left: "Bad place to keep money", right: "Safe place to keep money", difficulty: "easy", category: "work" },
  { left: "Worst side hustle", right: "Best side hustle", difficulty: "hard", category: "work" },
  { left: "Bad investment", right: "Great investment", difficulty: "hard", category: "work" },
  { left: "Worst boss trait", right: "Best boss trait", difficulty: "easy", category: "work" },
  { left: "Least lucrative degree", right: "Most lucrative degree", difficulty: "hard", category: "work" },
  { left: "Bad reason to quit a job", right: "Great reason to quit a job", difficulty: "hard", category: "work" },
  { left: "Worst remote work setup", right: "Best remote work setup", difficulty: "easy", category: "work" },
  { left: "Bad meeting topic", right: "Worth-the-meeting topic", difficulty: "hard", category: "work" },
  { left: "Worst office snack", right: "Best office snack", difficulty: "easy", category: "work" },

  // ─── Activities, Sports & Hobbies ─────────────────────────────────────
  { left: "Worst exercise", right: "Best exercise", difficulty: "hard", category: "activities" },
  { left: "Least transferable skill", right: "Most transferable skill", difficulty: "hard", category: "activities" },
  { left: "Bad sport to watch on TV", right: "Best sport to watch on TV", difficulty: "hard", category: "activities" },
  { left: "Worst hobby to take up at 40", right: "Best hobby to take up at 40", difficulty: "hard", category: "activities" },
  { left: "Least spectator-friendly sport", right: "Most spectator-friendly sport", difficulty: "hard", category: "activities" },
  { left: "Bad knitting project", right: "Impressive knitting project", difficulty: "hard", category: "activities" },
  { left: "Worst thing to lose mid-workout", right: "Funniest thing to lose mid-workout", difficulty: "easy", category: "activities" },
  { left: "Bad bowling lane name", right: "Great bowling lane name", difficulty: "hard", category: "activities" },
  { left: "Least meditative activity", right: "Most meditative activity", difficulty: "hard", category: "activities" },
  { left: "Worst golf course feature", right: "Best golf course feature", difficulty: "hard", category: "activities" },

  // ─── Holidays & Events ────────────────────────────────────────────────
  { left: "Worst Christmas gift", right: "Best Christmas gift", difficulty: "easy", category: "events" },
  { left: "Bad Valentine's gift", right: "Sweet Valentine's gift", difficulty: "easy", category: "events" },
  { left: "Worst New Year's resolution", right: "Best New Year's resolution", difficulty: "hard", category: "events" },
  { left: "Bad Halloween candy", right: "Best Halloween candy", difficulty: "easy", category: "events" },
  { left: "Worst Thanksgiving side dish", right: "Best Thanksgiving side dish", difficulty: "hard", category: "events" },
  { left: "Bad birthday party theme for a 7-year-old", right: "Great birthday party theme for a 7-year-old", difficulty: "easy", category: "events" },
  { left: "Worst event to be late for", right: "Acceptable event to be late for", difficulty: "easy", category: "events" },
  { left: "Bad fireworks display", right: "Amazing fireworks display", difficulty: "hard", category: "events" },
  { left: "Worst Easter basket item", right: "Best Easter basket item", difficulty: "easy", category: "events" },
  { left: "Bad gift card", right: "Great gift card", difficulty: "hard", category: "events" },

  // ─── Body, Health & Senses ────────────────────────────────────────────
  { left: "Worst body part to break", right: "Least bad body part to break", difficulty: "hard", category: "body" },
  { left: "Worst place to get a cramp", right: "Acceptable place to get a cramp", difficulty: "easy", category: "body" },
  { left: "Bad sleep position", right: "Best sleep position", difficulty: "easy", category: "body" },
  { left: "Worst itch", right: "Most satisfying itch", difficulty: "easy", category: "body" },
  { left: "Bad place to stub your toe", right: "Acceptable place to stub your toe", difficulty: "hard", category: "body" },
  { left: "Least ergonomic", right: "Most ergonomic", difficulty: "hard", category: "body" },
  { left: "Worst diet advice", right: "Best diet advice", difficulty: "hard", category: "body" },
  { left: "Bad symptom to ignore", right: "OK symptom to ignore", difficulty: "easy", category: "body" },
  { left: "Worst sneeze timing", right: "OK sneeze timing", difficulty: "hard", category: "body" },
  { left: "Bad way to wake up", right: "Great way to wake up", difficulty: "easy", category: "body" },

  // ─── Imagination & Abstract ───────────────────────────────────────────
  { left: "Bad immortality scenario", right: "Great immortality scenario", difficulty: "hard", category: "imagination" },
  { left: "Least useful magic spell", right: "Most useful magic spell", difficulty: "hard", category: "imagination" },
  { left: "Worst time travel destination", right: "Best time travel destination", difficulty: "hard", category: "imagination" },
  { left: "Worst alien to meet", right: "Best alien to meet", difficulty: "hard", category: "imagination" },
  { left: "Bad mutation", right: "Cool mutation", difficulty: "easy", category: "imagination" },
  { left: "Worst dragon", right: "Coolest dragon", difficulty: "hard", category: "imagination" },
  { left: "Bad robot uprising trigger", right: "Reasonable robot uprising trigger", difficulty: "hard", category: "imagination" },
  { left: "Worst dystopia", right: "Least bad dystopia", difficulty: "hard", category: "imagination" },
  { left: "Bad fantasy weapon", right: "Iconic fantasy weapon", difficulty: "hard", category: "imagination" },
  { left: "Worst portal destination", right: "Best portal destination", difficulty: "hard", category: "imagination" },
  { left: "Worst decade to be a teenager", right: "Best decade to be a teenager", difficulty: "hard", category: "imagination" },
  { left: "Bad year for technology", right: "Great year for technology", difficulty: "hard", category: "imagination" },
  { left: "Least nostalgic decade", right: "Most nostalgic decade", difficulty: "hard", category: "imagination" },
  { left: "Worst trend", right: "Best trend", difficulty: "hard", category: "imagination" },
  { left: "Bad century to live through", right: "Great century to live through", difficulty: "easy", category: "imagination" },
  { left: "Least relevant fact", right: "Most relevant fact", difficulty: "hard", category: "imagination" },
  { left: "Worst year to be born", right: "Best year to be born", difficulty: "hard", category: "imagination" },
  { left: "Bad timing", right: "Perfect timing", difficulty: "hard", category: "imagination" },
  { left: "Worst thing to be early for", right: "Best thing to be early for", difficulty: "hard", category: "imagination" },
  { left: "Bad thing to make a comeback", right: "Welcome comeback", difficulty: "hard", category: "imagination" },
  { left: "Worst hiding spot", right: "Best hiding spot", difficulty: "hard", category: "imagination" },
  { left: "Bad thing to find under your bed", right: "Cool thing to find under your bed", difficulty: "easy", category: "imagination" },
  { left: "Worst smell in a car", right: "Best smell in a car", difficulty: "easy", category: "imagination" },
  { left: "Bad weather", right: "Perfect weather", difficulty: "easy", category: "imagination" },
  { left: "Least convincing lie", right: "Most convincing lie", difficulty: "hard", category: "imagination" },
  { left: "Worst thing to hear at 3am", right: "Comforting thing to hear at 3am", difficulty: "easy", category: "imagination" },
  { left: "Bad place to take a nap", right: "Acceptable place to take a nap", difficulty: "easy", category: "imagination" },
  { left: "Worst thing to find in your soup", right: "Funniest thing to find in your soup", difficulty: "hard", category: "imagination" },
  { left: "Bad superpower drawback", right: "Coolest superpower drawback", difficulty: "hard", category: "imagination" },
  { left: "Worst thing to be confident about", right: "Best thing to be confident about", difficulty: "hard", category: "imagination" },
];
